server:
  port: 9090
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:~/community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
github:
  client:
    id: d217cbd0705a004e0bdb
    secret: d4633dd492d50a04c3c715f37739af8e736539e7
  redirect:
    uri: http://localhost:9090/callback

mybatis:
  type-aliases-package: com.wd.mapper